sculpin_content_types:
  posts:
    permalink: en/tech-blog/:year/:month/:day/:filename.html
  familie:
    permalink: familie/:year/:month/:day/:filename.html
  reiseblog:
    permalink: de/reiseblog/:year/:month/:day/:filename.html
